install.packages("sqldf")
library("sqldf")

stu<-read.csv(file.choose())

stu
View(sqldf("select * from stu"))
sqldf("select count(*) from stu")
sqldf("select * from stu where marks>80")
sqldf("select * from stu where marks <80")
sqldf("select * from stu where name='Veer'")
sqldf("select * from stu where marks==45")
sqldf("select name from stu where marks==45")
sqldf("select distinct name from stu")
min(stu$marks)
max(stu$marks)
nrow(stu)
ncol(stu)
nrow(stu[stu$marks==33,])
nrow(stu[stu$marks>33,])
sqldf("select * from stu limit 3")
sqldf("select * from stu order by name desc limit 4")
sqldf("select name,marks from stu order by name desc,marks")
sqldf("select * from stu order by name desc")
sqldf("select * from stu where name like '%s'")
sqldf("select * from stu where name like 'V%'")
sqldf("select name as N,marks as M from stu")
sqldf("select sum(marks) from stu")
sqldf("select roll_no,name from stu order by name")
sqldf("select * from stu where name like'%r'")
sqldf("select name, marks from stu where name like 'A%'")
sqldf("select name as SN,marks as Grade,roll_no as Reg_No from stu")
